version: '3.7'
services:
  mongo: 
   image: mongo
   ports: 
    - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  frontend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend